### PR TITLE
Update README.md to fix Discord invite

### PR DESCRIPTION
**Pull request by fancythedeveloper**
(How do I rebase a branch onto the HEAD of a fork?)

### CODE REVIEW

**Comment by AstrlJelly** [comment]
this has a lot of extra commits, mind cherry picking the single commit to a new branch and re-pring?

**Comment by fancythedeveloper** [comment]
> this has a lot of extra commits, mind cherry picking the single commit to a new branch and re-pring?

That's what I tried doing, but I'm not sure exactly how

**Comment by fancythedeveloper** [comment]
It would be a LOT more convenient if I had a different repo for Plus but GitHub wouldn't let me

**Comment by fancythedeveloper** [comment]
Since #7 is just this but fixed, I'll close this

**Pull request closed without merging**
